# This is a basic workflow to help you get started with Actions

name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Merge all stages into single file
      run: |
        cat stages/*.sh > install.sh
        sed 's/source .\/000-helpers.sh//g' install.sh
        
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        # Artifact name
        name: Install Script
        # Directory containing files to upload
        path: install.sh
